openapi: 3.0.0
info:
  title: 产品信息 API
  version: 1.0.0
  description: 聚千保保险产品信息查询服务
servers:
  - url: https://api.jqbao168.com/v1
    description: 生产环境
paths:
  /api/products/{productCode}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../api-reference/products/{productCode}.json'