openapi: 3.0.0
info:
  title: 产品信息 API
  version: 1.0.0
  description: |
    通过产品代码获取保险产品的详细信息。
paths:
  /products/{productCode}:
    get:
      summary: 获取产品信息
      parameters:
        - name: productCode
          in: path
          required: true
          schema:
            type: string
          description: 产品代码
          example: "LB-GZ-BJ-2024"
      responses:
        '200':
          description: 成功返回产品信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success"
                  data:
                    $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        basicInfo:
          type: object
          properties:
            productCode:
              type: string
              example: "LB-GZ-BJ-2024"
            productName:
              type: string
              example: "利宝保险（北京）雇主责任险（1-5类Jqb）"