openapi: 3.0.0
info:
  title: 产品信息 API
  version: 1.0.0
  description: 聚千保保险产品信息查询服务
paths:
  /products/{productCode}:
    get:
      summary: 获取产品信息
      parameters:
        - name: productCode
          in: path
          required: true
          schema:
            type: string
          example: "LB-GZ-BJ-2024"
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  productName:
                    type: string
                    example: "利宝保险（北京）雇主责任险"